title: stamping-app
hero_image: images/banner.png
description: stamping-app description
version: 4
listed: false
copyedit: false
last_tested: "2020-07-22"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
