title: Stamping app
hero_image: images/banner.png
description: Create your own project to make an app interface for the  user to select - it’s your choice
version: 1
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Choose your theme
  - title: App interface
  - title: Ingredients or equivalent
  - title: Buttons
  - title: Share your project
  - title: Reflect on your project
  - title: What next?
