title: Stamping sprites
hero_image: images/banner.png
description: Create your own project to try to change someone’s mood whether it be relaxing, energising, funny, inspiring or something else - it’s your choice
version: 1
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Choose your theme
  - title: Get a sprite moving
  - title: Add more sprites
  - title: More ideas
  - title: Share your project
  - title: Reflect on your project
  - title: What next?
