title: Stamping app
hero_image: images/banner.png
description: Create your own project to make an app interface for a user to design a picture or pattern
version: 1
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Develop your theme
  - title: App interface
  - title: Ingredients sprite or equivalent
  - title: Buttons
  - title: Share your project
  - title: Reflect on your project
  - title: What next?
